services:
  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/src/
      - ./app/data:/src/data/
    restart: on-failure
    container_name: test-weather-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:create_app", "--host", "0.0.0.0", "--port", "8000", "--factory"]

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb_local
    expose:
      - 8000
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
