version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/src/
    restart: on-failure
    container_name: test-weather-app
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:create_app", "--host", "0.0.0.0", "--port", "8000", "--factory"]
